name: d2r_items_image_update
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  dotenv: ^4.0.1
  http: ^0.13.4
  mongo_dart: ^0.7.4+1
  puppeteer: ^2.11.0
  supabase: ^0.3.4+1

dev_dependencies:
  box_generator: ^0.3.3+2
  build_runner: ^2.1.11
  lints: ^2.0.0
  test: ^1.16.0
